# Generated by Django 5.2 on 2025-11-21 18:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="CivicLink", max_length=100, verbose_name="site name"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, verbose_name="site description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="favicon"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="content"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta description"),
                ),
            ],
            options={
                "verbose_name": "static page",
                "verbose_name_plural": "static pages",
                "ordering": ["title"],
            },
        ),
    ]
